"""transactions with time

Revision ID: 8cd539bc47cc
Revises: b17bbcdafc38
Create Date: 2020-04-19 14:46:07.927669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd539bc47cc'
down_revision = 'b17bbcdafc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_transaction_time'), 'transaction', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_time'), table_name='transaction')
    op.drop_column('transaction', 'time')
    # ### end Alembic commands ###
