"""customers table

Revision ID: abc7cba452c0
Revises: 19ae65146d70
Create Date: 2020-04-18 16:13:25.017287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc7cba452c0'
down_revision = '19ae65146d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('account',
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('account_number'),
    sa.UniqueConstraint('account_number')
    )
    op.drop_index('ix_accounts_customer_id', table_name='accounts')
    op.drop_index('ix_accounts_name', table_name='accounts')
    op.drop_index('ix_accounts_surname', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_number', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('surname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('account_number'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index('ix_accounts_surname', 'accounts', ['surname'], unique=False)
    op.create_index('ix_accounts_name', 'accounts', ['name'], unique=False)
    op.create_index('ix_accounts_customer_id', 'accounts', ['customer_id'], unique=False)
    op.drop_table('account')
    op.drop_table('customer')
    # ### end Alembic commands ###
